# Generated by Django 4.1.5 on 2023-02-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
