# Generated by Django 4.1.5 on 2023-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence1', '0002_alter_employeedetail_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
