# Generated by Django 4.1.5 on 2023-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence1', '0003_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentemployee',
            name='in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='presentemployee',
            name='out_time',
            field=models.DateTimeField(null=True),
        ),
    ]
