# Generated by Django 4.1.5 on 2023-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence1', '0004_alter_presentemployee_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentemployee',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentemployee',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
